// Code generated by tygo. DO NOT EDIT.

//////////
// source: images.go

export interface Image {
  data: string;
  id: string;
}

//////////
// source: tracks.go

export interface Track {
  id: string;
  name: string;
}
